version: "3.9"

services:
  naves_app:
    container_name: naves_app
    image: pee-naves-app:1.0.0
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://naves_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - naves_db
  naves_db:
    container_name: naves_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
